name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**' # backend 폴더 안의 파일이 변할 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{  secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/clean-sync/backend
            git pull origin main
            
            # 의존성 설치 (새로운 라이브러리 추가 대비)
            npm install
            
            # PM2로 서버 재시작 (이미 켜져있으면 reload)
            pm2 reload clean-sync-api || pm2 start project.js --name "clean-sync-api"
            
            # 상태 확인
            pm2 status