name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'collector/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/clean-sync
            git fetch origin main
            git reset --hard origin/main  # 이 줄이 핵심입니다! 강제로 깃허브와 똑같이 맞춥니다.
            pkill -f mqtt_to_db.py || true
            cd ~/clean-sync/collector
            nohup python3 -u mqtt_to_db.py &  
