name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**' # backend 폴더 안의 파일이 변할 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{  secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/clean-sync/backend
            git pull origin main
            
            # 수집기(Python)는 건드리지 않고 백엔드만 관리
            npm install
            
            # pm2 이름이 정확해야 합니다 (clean-sync-api)
            pm2 reload clean-sync-api || pm2 start project.js --name "clean-sync-api"
            
            # 저장 (재부팅 대비)
            pm2 save